version: "3.7"

services:
  db:
    image: rethinkdb
    volumes:
      - data-rethinkdb:/data

  backend:
    image: driving-manager-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - db

  frontend:
    image: driving-manager-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:3000"

volumes:
  data-rethinkdb:
